### ISSUE TITLE
Error starting the project

### ISSUE THREAD

**Issue by khurana3192** [TwilioDevEd/browser-dialer-vue#3]
> browser-dailer-vue@1.0.0 start /Users/prateekkhurana/Downloads/browser-dialer-vue-master
> node index.js

/Users/prateekkhurana/Downloads/browser-dialer-vue-master/index.js:5
const { urlencoded } = require('body-parser');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! browser-dailer-vue@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser-dailer-vue@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the browser-dailer-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs browser-dailer-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls browser-dailer-vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/prateekkhurana/Downloads/browser-dialer-vue-master/npm-debug.log

**Comment by khurana3192** [comment]
Updating node solved the issue.
